### ISSUE TITLE
Support templates root

### ISSUE THREAD

**Issue by javierav** [jimsynz/hamlbars#23]
Like ember-rails do: https://github.com/emberjs/ember-rails#architecture

If I have this file app/assets/javascripts/templates/admin_panel.hamlbars, the translated version is:

Ember.TEMPLATES['templates/admin_panel'] = "...";

I think that you could do add some logic like Hamlbars::Template.templates_root = 'templates' and the result be: 

Ember.TEMPLATES['admin_panel'] = "...";

**Comment by jimsynz** [comment]
Sounds great, as long as it's not a breaking change.  Feel free to send a PR.

**Comment by machty** [comment]
The solution seems simple enough, so I started working on this, and then I realized it would cut out a particular use case for a project I'm working on. Basically, it would be nice if there were someway to specify a templates_root based on the root JS file that's being compiled, rather than specifying a one-size-fits-all template root. The use case in mind: I have a Rails app that servers two different Ember apps, a desktop version for Advertisers and a mobile version for other users. I have two different root JS files, one for each, which each respectively include a different directory that houses all the code. This means that depending on which root JS files I'm loading, the path that hamlbars comes up with will either be 'advertisers/templates/yadda' or 'users/templates/yadda'. You can't really use a one-size-fits-all template root in this case unless there were some way for this to be configured per JS file. 

What do you guys think is a good way to address this issue? Is it a notable-enough use case to take into account for such an enhancement?

**Comment by jimsynz** [comment]
To be honest, I don't think this is a Hamlbars concern - I would think this is an app concern.  Seriously I would add a `before_filter` check in my `ApplicationController` for which app I need to serve and have it modify the arguments to `javascript_include_tag` to include a link to the relevant Sprockets JS manifest.

If you're really that stressed about typing a few extra characters in when creating views then add extra asset paths in `Rails.application.config.assets.paths`, which would give you the behaviour you're wanting for free (or at least I'm pretty sure it would).

**Comment by machty** [comment]
Yeah, that'd work. I already have it branching properly via another mechanism. Just thought I'd DRY it out even more.

**Comment by jimsynz** [comment]
I'm not adverse to you doing that and sending a PR, I'm just not entirely convinced that there is a cleaner way of doing it without making it non-obvious what is going on if anyone else should have to work with it.

**Comment by jimsynz** [comment]
So, I've been working in the v2.0 branch to see what it's like using other gems for the compilation, and I noticed that ember-rails is doing this, if I have a file `templates/mytemplate.hbs.hamlbars` then it loads it into Ember.TEMPLATES as 'mytemplate'. Two birds with one stone :)

**Comment by machty** [comment]
Nice! I'll definitely be making the switch
