### ISSUE TITLE
Planing for 1.1 Release.

### ISSUE THREAD

**Issue by jimsynz** [jimsynz/hamlbars#26]
@aaronjensen @blakink @joliss I'm planning on cleaning up the remaining issues and doing a 1.1 release some time this month.  Can I have some comments or thoughts from you guys on what you think needs doing?

I am seriously thinking of ripping out a lot of the code we have here and instead depending on projects like `haml_assets` and `handlebars_assets` and `ember-rails` to do all the work that needs working. Thoughts?

**Comment by inkstak** [comment]
Hi,

I didn't used Handlebars these last days, so I have no idea about what I can need.
However, about the dependencies, you must exclude ember-rails. I used Handlebars without EmberJS, so I don't see why I should depend on.

**Comment by aaronjensen** [comment]
Makes sense to me to take on dependencies from handlebars_assets and haml_assets, though it could very well be easier for you not to… the code you're thinking about ripping out is already written, and it's nice not to depend on the internal api of other projects you don't control… I'm not sure about the ember-rails dependency though, what do you need from that?

**Comment by jimsynz** [comment]
Mainly what I want to depend on ember-rails and handlebars_assets for is the runtime javascript that is needed for compilation. Keeping a copy in hamlbars and in sync with upstream seems like a waste of time when others are already doing the work.
It looks like handlebars_assets doesn't support compiling templates for ember, but that seems to be the most common use case (that I get feedback about, anyway).

**Comment by aaronjensen** [comment]
Any way to extract the things that are common to them into a gem that you can all depend on? Just curious since that seems like a better way than depending on projects that may have different uses.

**Comment by joliss** [comment]
Regarding precompilation, it seems to me that there are really two separate issues:
- Compiling Handlebars without Ember (Handlebars.precompile): To my understanding hamlbars does this already, but perhaps we can rely on handlebars_assets instead.
- Compiling Handlebars with Ember (Ember.Handlebars.precompile): You have to load ember-handlebars to do this, and it needs to be the same Ember version that you're using in your app. I think bundling Ember is out of scope for hamlbars, and it would be problematic since there could be a version mismatch. So the only sane option I see is relying on ember-rails and calling into its precompilation.

**Comment by jimsynz** [comment]
@joliss I don't believe that the Ember handlebars code has changed in a long while, making it reasonably safe to use, and why I had suggested depending on ember-rails - it might be better to just look for ember rails and offer the ability to compile the assets using it if it's present.

**Comment by joliss** [comment]
Right, that's what I was thinking -- detect at runtime if ember-rails is around. Here's code from Capybara that does this with launchy: https://github.com/jnicklas/capybara/blob/d76987f121/lib/capybara/util/save_and_open_page.rb#L24
